# Generated by Django 4.2.17 on 2025-01-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_rename_item_auction_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1234, upload_to='images/'),
            preserve_default=False,
        ),
    ]
