# Generated by Django 5.1.4 on 2025-01-14 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='last_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_bid_auction', to='auction.user'),
        ),
    ]
