# Generated by Django 5.1.4 on 2025-01-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auction_last_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
