# Generated by Django 5.1.5 on 2025-01-22 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_alter_auction_last_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='last_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_bid_auction', to='auction.user'),
        ),
    ]
